version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      # SPRING_PROFILES_ACTIVE: Hvis man vil have flere miljøer = prod, dev, docker
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}

  mysql:
    image: mysql:latest
    container_name: adventurexp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

    ports:
      - "127.0.0.1:3307:3306"   # containerens port 3306 mappes til vores lokale 3307
    volumes:
      - mysql_data:/var/lib/mysql # Bruger volume'et mysql_data

volumes:
  mysql_data: # Opretter docker-volume med navnet mysql_data



